# Generated by Django 3.2.3 on 2023-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('uname', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('umail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('profile', models.ImageField(blank=True, default='', help_text='Dimension 600px X 671px', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umail', models.TextField()),
                ('uspass', models.TextField()),
            ],
        ),
    ]
